### Create Product
POST http://localhost:8080/shop/products
Content-Type: application/json

{
  "categoryDTO": {
    "type": "TECHNIC"
  },
  "number": "42199",
  "elements": 1999,
  "price": 199.99
}

### Update Product
PUT http://localhost:8080/shop/products/1
Content-Type: application/json

{
  "id": 1,
  "categoryDTO": {
    "type": "TECHNIC"
  },
  "number": "42199",
  "elements": 1999,
  "price": 100.00
}

### Get product by ID
GET http://localhost:8080/shop/products/1

### Get all products
GET http://localhost:8080/shop/products/

### Delete product
DELETE http://localhost:8080/shop/products/1